version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./frontend/nginx/log:/var/log/nginx
    java:
        build: backend_java
        container_name: java
        volumes:
            - ./app:/var/www:cached
    python:
        build: backend_python
        container_name: python
        volumes:
          - ./app:/var/www:cached
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5433:5432"
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgres:/var/lib/postgres
        environment:
            POSTGRES_DB: electrocar_dev
            POSTGRES_USER: delphi
            POSTGRES_PASSWORD: minidelphi
        healthcheck:
            test: [ "CMD", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10