version: '1.4'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d:ro
            - ./app:/var/www
            - ./docker/nginx/log:/var/log/nginx
    java:
        build: docker/java
        container_name: java
        links:
            - postgres
        volumes:
            - ./app:/var/www:cached
            - ./docker/java/conf.d:/usr/local/etc/java/custom.d
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5433:5432"
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/postgres:/var/lib/postgres
        environment:
            POSTGRES_DB: electrocar_dev
            POSTGRES_USER: delphi
            POSTGRES_PASSWORD: minidelphi
        healthcheck:
            test: [ "CMD", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
    flask:
        build: ./docker/flask
        container_name: flask
        ports:
            - "5000:5000"
        volumes:
            - ./app:/var/www
